### ISSUE TITLE
Create UseCase Description

### ISSUE THREAD

**Issue by oat431** [coalingot/coalingot-project-backend#1]
Crease Use Case Description

- Register : @Pondae 
- Login : @Pondae 
- Post Auction Item : @PasakonPJ 
- Submit Auction Price : @Pondae 
- View Auction Details : @PasakonPJ

**Comment by Pondae** [comment]
finished

**Comment by PasakonPJ** [comment]
Done use case description

**Comment by Pondae** [comment]
https://docs.google.com/document/d/12CR4xEvhkKkqofMpFtPQabaOaba9hn1Bsp9kgCQHRdw/edit
